# Generated by Django 4.2.2 on 2023-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_phone',
            field=models.IntegerField(null=True),
        ),
    ]
