# Generated by Django 4.2.2 on 2023-08-09 20:14

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_title', models.CharField(max_length=50)),
                ('gt_price', models.CharField(max_length=50)),
                ('gt_des', tinymce.models.HTMLField()),
                ('gt_image', models.FileField(default=None, max_length=250, null=True, upload_to='gtimages/')),
                ('gt_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='gt_title', unique=True)),
            ],
        ),
    ]
