# Generated by Django 4.2.2 on 2023-08-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gift',
            new_name='giftModel',
        ),
    ]
