# Generated by Django 4.2.2 on 2023-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactenquiry_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
