# Generated by Django 4.2.2 on 2023-08-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='news_email',
            new_name='newsEmail',
        ),
    ]
