# Generated by Django 4.2.2 on 2023-08-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_news_email_newsletter_newsemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsletter',
            new_name='newsletterModel',
        ),
    ]
