# Generated by Django 4.2.2 on 2023-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_newsletter_newslettermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermodel',
            name='newsEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
