# Generated by Django 4.2.2 on 2023-08-18 19:56

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_des', models.TextField()),
                ('blog_date', models.DateField(default=datetime.date.today, null=True)),
                ('blog_img', models.FileField(default=None, max_length=250, null=True, upload_to='blimages/')),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
            ],
        ),
    ]
