# Generated by Django 4.2.2 on 2023-08-18 20:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_des',
            field=tinymce.models.HTMLField(),
        ),
    ]
