# Generated by Django 4.2.2 on 2023-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_blog_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
