# Generated by Django 4.2.2 on 2023-07-25 13:26

import autoslug.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_title', models.CharField(max_length=50)),
                ('ch_price', models.CharField(max_length=50)),
                ('ch_des', tinymce.models.HTMLField()),
                ('ch_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ch_title', unique=True)),
            ],
        ),
    ]
